apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T11:41:45Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3157"
  uid: 80763217-ec14-4757-88f3-11c58c5bef31
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.143.203
  clusterIPs:
  - 10.110.143.203
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32237
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
